name: Release Service

on:
  push:
    tags: "client-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.*
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release
      
      - name: Create the package - MyJetTools.SettingsManager.Client
        run: dotnet pack --configuration Release MyJetTools.SettingsManager.Client/MyJetTools.SettingsManager.Client.csproj /p:Version=${GITHUB_REF#refs/tags/client-}
        
      - name: Publish the package
        run: dotnet nuget push MyJetTools.SettingsManager.Client/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}